<a href="https://colab.research.google.com/github/ElLinares/curso-ia-para-economia/blob/main/clases/2_Programacion_en_Python/2_ejemplo_jupyter_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# **Conociendo Jupyter Notebook**

Se utiliza Python 3.13.5

## Importar librerías

In [2]:
import numpy as np
import pandas as pd

## Ajustar formato visualización

In [4]:
# Aumentar número de columnas que se pueden ver
# Que muestre 500 columnas máximo
pd.options.display.max_columns = 500
# Que muestre todas las columnas
pd.options.display.max_columns = None

In [5]:
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Cargar base de datos

In [7]:
df = pd.read_csv("Base_municipios.txt", sep="|", decimal=',' , encoding= 'utf-8', converters={'Cod. Municipio': str})
df.head()

,Cod. Municipio,Departamento,Municipio,Población municipio,Subregión PDET,ZOMAC,Valor agregado municipio,% Act. primarias municipio,% Act. secundarias municipio,% Act. terciarias municipio,% pobl. con educación media municipio,% pobl. con edu. técnica/tecnología municipio,% pobl. con pregrado municipio,% pobl. con posgrado municipio,% pobreza municipio,% informalidad municipio,% mujeres municipio,% jóvenes municipio,% pobl. con discapacidad municipio,% grupos étnicos municipio,% pobl. campesina municipio,% pobl. LGBT municipio
0,05001,Antioquia,Medellín,2572350,NaN,0,"66,432.28",0.18,20.06,79.76,26.54,10.34,11.83,3.47,12.80,71.00,52.91,24.48,6.27,2.59,1.90,1.74
1,05002,Antioquia,Abejorral,21109,NaN,1,314.20,45.43,6.37,48.19,12.80,2.46,1.73,0.85,40.60,87.50,47.79,20.51,16.05,0.36,NaN,NaN
2,05004,Antioquia,Abriaquí,2804,NaN,1,38.48,37.04,6.45,56.51,21.40,4.96,2.69,1.07,34.80,87.60,45.79,22.04,16.72,2.04,NaN,NaN
3,05021,Antioquia,Alejandría,4874,NaN,1,67.95,18.02,6.89,75.08,14.64,5.57,2.92,0.73,31.90,87.10,50.39,20.11,8.10,0.31,NaN,NaN
4,05030,Antioquia,Amagá,31851,NaN,0,635.93,6.84,46.20,46.96,22.83,5.97,2.95,0.70,22.90,69.50,50.92,23.26,9.02,0.52,NaN,NaN

## Revisar contenido base de datos

In [8]:
# Ver el nombre de todas las columnas
df.columns

Index(['Cod. Municipio', 'Departamento', 'Municipio', 'Población municipio',
       'Subregión PDET', 'ZOMAC', 'Valor agregado municipio',
       '% Act. primarias municipio', '% Act. secundarias municipio',
       '% Act. terciarias municipio', '% pobl. con educación media municipio',
       '% pobl. con edu. técnica/tecnología municipio',
       '% pobl. con pregrado municipio', '% pobl. con posgrado municipio',
       '% pobreza municipio', '% informalidad municipio',
       '% mujeres municipio', '% jóvenes municipio',
       '% pobl. con discapacidad municipio', '% grupos étnicos municipio',
       '% pobl. campesina municipio', '% pobl. LGBT municipio'],
      dtype='object')

In [9]:
# Ver número de filas y columnas
df.shape

(1122, 22)

In [10]:
# Ver la cantidad de filas del df
len(df)

1122

In [11]:
# Ver los tipos de datos de cada columna
df.dtypes

Cod. Municipio                                    object
Departamento                                      object
Municipio                                         object
Población municipio                                int64
Subregión PDET                                    object
ZOMAC                                              int64
Valor agregado municipio                         float64
% Act. primarias municipio                       float64
% Act. secundarias municipio                     float64
% Act. terciarias municipio                      float64
% pobl. con educación media municipio            float64
% pobl. con edu. técnica/tecnología municipio    float64
% pobl. con pregrado municipio                   float64
% pobl. con posgrado municipio                   float64
% pobreza municipio                              float64
% informalidad municipio                         float64
% mujeres municipio                              float64
% jóvenes municipio                              float64
% pobl. con discapacidad municipio               float64
% grupos étnicos municipio                       float64
% pobl. campesina municipio                      float64
% pobl. LGBT municipio                           float64
dtype: object

In [ ]:
# Ver la cantidad de filas y columnas, el nombre todas las columnas, el tipo de datos y si tiene nulos